name: iOS Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  issues: write

env:
  XCODE_VERSION: '15.2'
  DEVELOPER_DIR: /Applications/Xcode_15.2.app/Contents/Developer

jobs:
  build:
    name: Build and Test
    runs-on: macos-14
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Select Xcode Version
        run: |
          sudo xcode-select -s /Applications/Xcode_15.2.app
          xcodebuild -version
          echo "Selected Xcode path: $(xcode-select -p)"

      - name: Cache Homebrew
        uses: actions/cache@v4
        with:
          path: |
            ~/Library/Caches/Homebrew
            ~/Library/Caches/Homebrew/downloads
          key: ${{ runner.os }}-brew-${{ hashFiles('.github/workflows/ios_build_and_deploy.yml') }}
          restore-keys: |
            ${{ runner.os }}-brew-

      - name: Install XcodeGen
        run: brew install xcodegen

      - name: Cache Swift packages
        uses: actions/cache@v4
        with:
          path: |
            .build
            ~/Library/Developer/Xcode/DerivedData/**/SourcePackages/checkouts
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Cache DerivedData
        uses: actions/cache@v4
        with:
          path: ~/Library/Developer/Xcode/DerivedData
          key: ${{ runner.os }}-derived-data-${{ hashFiles('project.yml') }}
          restore-keys: |
            ${{ runner.os }}-derived-data-

      - name: Generate Xcode project
        run: xcodegen generate

      - name: Build iOS App
        id: build
        run: |
          set -o pipefail && xcodebuild clean build \
            -project SwiftUITest4.xcodeproj \
            -scheme SwiftUITest4 \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.2' \
            -configuration Debug \
            -derivedDataPath ~/Library/Developer/Xcode/DerivedData \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO | xcpretty

      - name: Upload Build Artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: debug-build
          path: ~/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
          retention-days: 5

      - name: Create Build Status Issue
        if: always()
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const run_id = context.runId;
            const run_url = `https://github.com/${owner}/${repo}/actions/runs/${run_id}`;
            const status = '${{ job.status }}';
            const sha = context.sha;
            
            const buildLogs = `
            ### Build Status: ${status}
            
            **Commit:** ${sha}
            **Workflow Run:** [View build details](${run_url})
            
            ${status === 'success' ? '✅ Build completed successfully' : '❌ Build failed'}
            
            <details>
            <summary>Build Information</summary>
            
            - **Repository:** ${owner}/${repo}
            - **Branch:** ${context.ref.replace('refs/heads/', '')}
            - **Triggered by:** ${context.eventName}
            - **Xcode Version:** ${process.env.XCODE_VERSION}
            </details>
            `;
            
            await github.rest.issues.create({
              owner,
              repo,
              title: `Build Status: ${status}`,
              body: buildLogs,
              labels: ['build-status', status.toLowerCase()]
            });
